/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripa3l;

import java.awt.Color;
import java.awt.Component;
import skripa3l.Koneksi;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Objects;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
/**
 *
 * @author KAMPRTO
 */
public final class MasterA3L extends javax.swing.JFrame {
    DefaultTableModel tabModel;
    Object[] kolom;
    Dimension OD = Toolkit.getDefaultToolkit().getScreenSize();
    SearchRenderer renderer = new SearchRenderer();
    private JFrame frame = new JFrame();
   
    /**
     * Creates new form MasterA3L
     */
    public MasterA3L() {
        initComponents();
        
        setTitle("Master A3L");
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocation(OD.width / 2 - getWidth() / 2, OD.height / 2 - getHeight() / 2);
        kolom = new Object[]{"Kode A3L", "Kota", "Alamat", "Telepon"};
        tabModel = new DefaultTableModel(null, kolom);
        jTable1.setModel(tabModel);
      
        setAwalForm();
        autoNumber();
        txtCari.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                fireDocumentChangeEvent();
            }

            public void removeUpdate(DocumentEvent e) {
                fireDocumentChangeEvent();
            }

            public void changedUpdate(DocumentEvent e) {
            }
        });
        fireDocumentChangeEvent();
        jTable1.setDefaultRenderer(Object.class, renderer);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtA3L = new javax.swing.JTextField();
        txtKota = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBersih = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Master A3L");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Kode A3L");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Kota");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Alamat");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Telepon");

        txtA3L.setBackground(new java.awt.Color(204, 204, 204));

        txtKota.setBackground(new java.awt.Color(204, 204, 204));

        txtAlamat.setBackground(new java.awt.Color(204, 204, 204));

        txtTelepon.setBackground(new java.awt.Color(204, 204, 204));

        txtCari.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode A3L", "Kota", "Alamat", "Telepon"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnBersih.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBersih.setText("Bersih");
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Cari");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtA3L)
                            .addComponent(txtKota)
                            .addComponent(txtAlamat)
                            .addComponent(txtTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSimpan)
                        .addGap(41, 41, 41)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtA3L, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (!txtA3L.getText().equals("") && !txtKota.getText().equals("") && !txtAlamat.getText().equals("") && !txtTelepon.getText().equals("")) {
            try {
                Koneksi objK = new Koneksi();
                Connection con = objK.getConnection();
                Statement st = con.createStatement();
                String sql = "Insert into master_a3l values('"
                        + txtA3L.getText() + "','"
                        + txtKota.getText()+ "','"
                        + txtAlamat.getText() + "','"
                        + txtTelepon.getText() + "')";
                int vHasil = st.executeUpdate(sql);
                if (vHasil > 0) {
                    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambah");
                }
                con.close();
                setAwalForm();
            } catch (SQLException | HeadlessException e) {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Isi Data Secara Lengkap");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        tampildaritable();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        // TODO add your handling code here:
         setAwalForm();
    }//GEN-LAST:event_btnBersihActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
         int confirm = JOptionPane.showOptionDialog(frame, 
                        "Apakah Anda Ingin Mengubah Data Ini ?", 
                        "Confirmation", JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (confirm == JOptionPane.YES_OPTION){
            try {
                Koneksi objK = new Koneksi();
                Connection con = objK.getConnection();
                Statement st = con.createStatement();//menulis statement harus melalui objek koneksi// langkah 3
                String sql = "Update master_a3l set kota='" + txtKota.getText()+ "', alamat='" + txtAlamat.getText()+ "', Telepon='" + txtTelepon.getText() + "' Where kode_bi='" + txtA3L.getText() + "';";
                int vHasil = st.executeUpdate(sql);//langkah 5, sql dari string yg dipakai untuk insert barang tadi
                if (vHasil > 0) {//langkah 6
                    JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                }
                setAwalForm();
                con.close();
            } catch (SQLException | HeadlessException e) {
                System.out.println(e.toString());
            }
        }
        else if (confirm == JOptionPane.NO_OPTION){
            setAwalForm();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showOptionDialog(frame, 
                        "Apakah Anda Ingin Menghapus Data Ini ?", 
                        "Confirmation", JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (confirm == JOptionPane.YES_OPTION){
            try {
                Koneksi objK = new Koneksi();
                Connection con = objK.getConnection();
                Statement st = con.createStatement();//menulis statement harus melalui objek koneksi// langkah 3
                String sql = "Delete from master_a3l Where " + "Kode_A3L='" + txtA3L.getText() + "'";
                int vHasil = st.executeUpdate(sql);//langkah 5, sql dari string yg dipakai untuk insert barang tadi
                if (vHasil > 0) {//langkah 6
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                }
                setAwalForm();
                con.close();
            } catch (SQLException | HeadlessException e) {

            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuUtama a = new MenuUtama();
        a.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    void setAwalForm() {
        txtA3L.setEnabled(false);
        txtKota.setText("");
        txtAlamat.setText("");
        txtTelepon.setText("");
        txtKota.requestFocus();
        btnBersih.setEnabled(true);
        btnHapus.setEnabled(false);
        btnSimpan.setEnabled(true);
        btnEdit.setEnabled(false);

        autoNumber();
        hapusTabel();
        tampilTabel();
    }
    
    void autoNumber() {
        try {
            Koneksi objK = new Koneksi();
            Connection con = objK.getConnection();
            Statement st = con.createStatement();
            String sql = "select * from master_a3l order by Kode_A3L";
            ResultSet rs = st.executeQuery(sql);
            if (rs.last()) {
                String sNo = rs.getString("Kode_A3L");
                int iNo = Integer.parseInt(sNo) + 1;
                txtA3L.setText(String.valueOf(iNo));
                rs.close();
                con.close();
            } else {
                txtA3L.setText("1");
            }

        } catch (Exception e) {
        }
    }
    
    void hapusTabel() {
        int brs = tabModel.getRowCount();
        for (int i = 0; i < brs; i++) {
            tabModel.removeRow(0);
        }
    }
    
     void tampilTabel() {
        try {
            Koneksi objK = new Koneksi();
            Connection con = objK.getConnection();
            Statement st = con.createStatement();
            String sql = "Select * from master_a3l order by Kode_A3L";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String Kode_A3L = rs.getString("Kode_A3L");
                String Kota = rs.getString("Kota");
                String Alamat = rs.getString("Alamat");
                String Telepon = rs.getString("Telepon");
                
                String[] data = {Kode_A3L, Kota, Alamat, Telepon};
                tabModel.addRow(data);
                TableColumn column;
                jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
                column = jTable1.getColumnModel().getColumn(0); 
                column.setPreferredWidth(55);
                column = jTable1.getColumnModel().getColumn(1); 
                column.setPreferredWidth(150); 
                column = jTable1.getColumnModel().getColumn(2); 
                column.setPreferredWidth(320); 
                column = jTable1.getColumnModel().getColumn(3); 
                column.setPreferredWidth(105);
                //System.out.println("data customer : "+data);
            }
            rs.close();
            con.close();
        } catch (SQLException | HeadlessException e) {

        }
    }
     
     void tampildaritable() {
        int row = jTable1.getSelectedRow();
        txtA3L.setText(jTable1.getValueAt(row, 0).toString());
        txtKota.setText(jTable1.getValueAt(row, 1).toString());
        txtAlamat.setText(jTable1.getValueAt(row, 2).toString());
        txtTelepon.setText(jTable1.getValueAt(row, 3).toString());
        btnSimpan.setEnabled(false);
        btnBersih.setEnabled(true);
        btnHapus.setEnabled(true);
        btnEdit.setEnabled(true);
        txtKota.requestFocus();
     }
     
     private void fireDocumentChangeEvent() {
        String pattern = txtCari.getText().trim();
        renderer.setPattern(pattern);
        jTable1.repaint();
    }
     
     class SearchRenderer implements TableCellRenderer {

        private final Color BACKGROUND_SELECTION_COLOR = new Color(220, 240,
                255);
        private final transient Highlighter.HighlightPainter highlightPainter = new DefaultHighlighter.DefaultHighlightPainter(
                Color.BLUE);
        private final JTextField txtCari = new JTextField();
        private String pattern = "";
        private String prev;

        public boolean setPattern(String str) {
            if (str == null || str.equals(pattern)) {
                return false;
            } else {
                prev = pattern;
                pattern = str;
                return true;
            }
        }
      public SearchRenderer() {
            super();
            txtCari.setOpaque(true);
            txtCari.setBorder(BorderFactory.createEmptyBorder());
            txtCari.setForeground(Color.BLACK);
            txtCari.setBackground(Color.WHITE);
            txtCari.setEditable(false);
        }

        @Override
        public Component getTableCellRendererComponent(JTable tabel,
                Object value, boolean isSelected, boolean hasFocus, int row,
                int column) {
            String txt = Objects.toString(value, "");
            Highlighter highlighter = txtCari.getHighlighter();
            highlighter.removeAllHighlights();
            txtCari.setText(txt);
            txtCari.setBackground(isSelected ? BACKGROUND_SELECTION_COLOR
                    : Color.WHITE);
            if (pattern != null && !pattern.isEmpty() && !pattern.equals(prev)) {
                Matcher matcher = Pattern.compile(pattern).matcher(txt);
                if (matcher.find()) {
                    int start = matcher.start();
                    int end = matcher.end();
                    try {
                        highlighter.addHighlight(start, end, highlightPainter);
                    } catch (BadLocationException e) {
                        e.printStackTrace();
                    }
                }
            }
            return txtCari;
        }
    }
    
//    public void lebarKolom(){ 
//        TableColumn column;
//        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
//        column = jTable1.getColumnModel().getColumn(0); 
//        column.setPreferredWidth(100);
//        column = jTable1.getColumnModel().getColumn(1); 
//        column.setPreferredWidth(200); 
//        column = jTable1.getColumnModel().getColumn(2); 
//        column.setPreferredWidth(50); 
//        column = jTable1.getColumnModel().getColumn(3); 
//        column.setPreferredWidth(150); 
//    }
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterA3L.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterA3L.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterA3L.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterA3L.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterA3L().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtA3L;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtKota;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
