/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package skripa3l;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import proses.Enkrip;

/**
 *
 * @author KAMPRTO
 */
public final class Transaksi extends javax.swing.JFrame {
    
    Object[] judul = {"No Kwitansi", "Tanggal", "Kode A3L", "Kota", "Telepon", "Kode Barang", "Nama Barang",  "Harga Satuan", "Kode Pengiriman", "Tujuan Pengiriman", "Jumlah Barang", "Jumlah Harga", "Harga Pengiriman"};
    DefaultTableModel tampil = new DefaultTableModel(null, judul);
    Dimension OD = Toolkit.getDefaultToolkit().getScreenSize();
    private Connection con;
    private Statement stat;
    private ResultSet res;
    private JFrame frame = new JFrame();
    private final Enkrip enkrip = new Enkrip();
    
    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
        setTitle("Transaksi");
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //this.getContentPane().setBackground(Color.lightGray);
        this.setLocation(OD.width / 2 - getWidth() / 2, OD.height / 3 - getHeight() / 3);
        tabeltransaksi.setModel(tampil);
        autoNumber();
        setAwalForm();
        tampilTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNoKwitansi = new javax.swing.JTextField();
        waktu = new com.toedter.calendar.JDateChooser();
        txtCariKodeA3L = new javax.swing.JTextField();
        txtKota = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        btnCariA3L = new javax.swing.JButton();
        txtCariBarang = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        txtHargaSatuan = new javax.swing.JTextField();
        txtJmlBarang = new javax.swing.JTextField();
        txtJmlHarga = new javax.swing.JTextField();
        txtTujuan = new javax.swing.JTextField();
        txtHrgKirim = new javax.swing.JTextField();
        btnCariBarang = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnDekrip = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        btnCariTujuan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeltransaksi = new javax.swing.JTable();
        txtCariPengiriman = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Transaksi");

        jLabel2.setText("No Kwitansi");

        jLabel3.setText("Tanggal");

        jLabel4.setText("Cari Cabang A3L");

        jLabel7.setText("Kota");

        jLabel8.setText("Telepon");

        jLabel5.setText("Cari Barang");

        jLabel9.setText("Nama Barang");

        jLabel10.setText("Harga Satuan");

        jLabel6.setText("Jumlah barang");

        jLabel11.setText("Jumlah Harga");

        jLabel12.setText("Harga Pengiriman");

        jLabel13.setText("Cari Tujuan ");

        btnCariA3L.setText("Pilih");
        btnCariA3L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariA3LActionPerformed(evt);
            }
        });

        txtJmlBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlBarangActionPerformed(evt);
            }
        });

        txtJmlHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlHargaActionPerformed(evt);
            }
        });

        txtHrgKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHrgKirimActionPerformed(evt);
            }
        });

        btnCariBarang.setText("Pilih");
        btnCariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBarangActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnDekrip.setText("Dekrip");
        btnDekrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDekripActionPerformed(evt);
            }
        });

        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        btnCariTujuan.setText("Pilih");
        btnCariTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariTujuanActionPerformed(evt);
            }
        });

        tabeltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeltransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeltransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabeltransaksi);

        jLabel14.setText("Cari Pengiriman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel8)
                                .addGap(52, 52, 52)
                                .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(50, 50, 50))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtJmlBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtJmlHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txtHrgKirim, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(txtNoKwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210)
                        .addComponent(jLabel5)
                        .addGap(34, 34, 34)
                        .addComponent(txtCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnCariBarang))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel3)
                        .addGap(50, 50, 50)
                        .addComponent(waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212)
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)
                        .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(txtCariKodeA3L, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnCariA3L)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel10)
                        .addGap(24, 24, 24)
                        .addComponent(txtHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210)
                        .addComponent(jLabel14)
                        .addGap(34, 34, 34)
                        .addComponent(txtCariPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCariTujuan))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnHapus)
                                .addGap(33, 33, 33)
                                .addComponent(btnDekrip, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(389, 389, 389)
                                .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtNoKwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(txtCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9))
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtCariKodeA3L, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnCariA3L, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))
                    .addComponent(txtHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCariTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14))
                            .addComponent(txtCariPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txtTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJmlBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJmlHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtHrgKirim, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDekrip, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariA3LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariA3LActionPerformed
        // TODO add your handling code here:
        From_A3L pop_A3L = new From_A3L(null, true);
        String resutl = pop_A3L.showDialogTampil();

        txtCariKodeA3L.setText(resutl);

        Koneksi objKoneksi = new Koneksi();
        try {
            Connection con = objKoneksi.getConnection();
            Statement st = con.createStatement();
            String sql = "select * from master_a3l "
                    + "where kode_a3l = '" + txtCariKodeA3L.getText() + "' ";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                txtKota.setText(rs.getString("Kota"));
                txtTelepon.setText(rs.getString("Telepon"));

            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnCariA3LActionPerformed

    private void txtJmlBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlBarangActionPerformed
        // TODO add your handling code here:
        int jmlganti, hrgsatuan, hrgkirim, jmlbayar;
        jmlganti = Integer.parseInt(txtJmlBarang.getText());
        hrgsatuan = Integer.parseInt(txtHargaSatuan.getText());
        hrgkirim = Integer.parseInt(txtHrgKirim.getText());
        jmlbayar = jmlganti * hrgsatuan + hrgkirim;
        txtJmlHarga.setText("" + jmlbayar);
        uang();
    }//GEN-LAST:event_txtJmlBarangActionPerformed

    private void txtJmlHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlHargaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtJmlHargaActionPerformed

    private void btnCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBarangActionPerformed
        // TODO add your handling code here:
        From_Barang pop_Service = new From_Barang(null, true);
        String resutl = pop_Service.showDialogTampil();

        txtCariBarang.setText(resutl);

        Koneksi objKoneksi = new Koneksi();
        try {
            Connection con = objKoneksi.getConnection();
            Statement st = con.createStatement();
            String sql = "select * from master_barang "
                    + "where Kode_Barang = '" + txtCariBarang.getText() + "' ";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                txtNamaBarang.setText(rs.getString("Nama_Barang"));
                txtHargaSatuan.setText(rs.getString("Harga"));

            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
                              
       
    }//GEN-LAST:event_btnCariBarangActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        int jmlganti, hrgsatuan, hrgkirim, jmlbayar;
        jmlganti = Integer.parseInt(txtJmlBarang.getText());
        hrgsatuan = Integer.parseInt(txtHargaSatuan.getText());
        hrgkirim = Integer.parseInt(txtHrgKirim.getText());
        jmlbayar = jmlganti * hrgsatuan + hrgkirim;
        txtJmlHarga.setText("" + jmlbayar);
        uang();
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnCariTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariTujuanActionPerformed
        // TODO add your handling code here:
        From_Pengiriman pop_Pengiriman = new From_Pengiriman(null, true);
        String resutl = pop_Pengiriman.showDialogTampil();

        txtCariPengiriman.setText(resutl);

        Koneksi objKoneksi = new Koneksi();
        try {
            Connection con = objKoneksi.getConnection();
            Statement st = con.createStatement();
            String sql = "select * from master_pengiriman "
                    + "where Kode_Pengiriman = '" + txtCariPengiriman.getText() + "' ";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                txtTujuan.setText(rs.getString("Tujuan_Pengiriman"));
                txtHrgKirim.setText(rs.getString("HrgPengiriman"));

            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_btnCariTujuanActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String password = "adminadmin";
        try {
            String text1 = enkrip.enkripText (txtCariKodeA3L.getText(), password);
            String text2 = enkrip.enkripText(txtKota.getText(), password);
            String text3 = enkrip.enkripText(txtTelepon.getText(), password);
            String text4 = enkrip.enkripText(txtCariBarang.getText(), password);
            String text5 = enkrip.enkripText(txtNamaBarang.getText(), password);
            String text6 = enkrip.enkripText(txtHargaSatuan.getText(), password);
            String text7 = enkrip.enkripText(txtCariPengiriman.getText(), password);
            String text8 = enkrip.enkripText(txtTujuan.getText(), password);  
            String text9 = enkrip.enkripText(txtJmlBarang.getText(), password);
            String text10 = enkrip.enkripText(txtJmlHarga.getText(), password);
            String text11 = enkrip.enkripText(txtHrgKirim.getText(), password);
            
            txtCariKodeA3L.setText(text1);
            txtKota.setText(text2);
            txtTelepon.setText(text3);
            txtCariBarang.setText(text4);
            txtNamaBarang.setText(text5);
            txtHargaSatuan.setText(text6);
            txtCariPengiriman.setText(text7);
            txtTujuan.setText(text8);
            
            txtJmlBarang.setText(text9);
            txtJmlHarga.setText(text10);
            txtHrgKirim.setText(text11);
            try {
//      Mengatur format tanggal
                SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
                String Tanggal = String.valueOf(format.format(waktu.getDate()));
                Koneksi objK = new Koneksi();
                Connection con = objK.getConnection();
                Statement st = con.createStatement();//menulis statement harus melalui objek koneksi// langkah 3

                String sql = "insert into transaksi values ('" + txtNoKwitansi.getText() + "','" + Tanggal + "','"
                        + txtCariKodeA3L.getText() + "','"
                        + txtKota.getText() + "','"
                        + txtTelepon.getText() + "','"
                        + txtCariBarang.getText() + "','"
                        + txtNamaBarang.getText() + "','"
                        + txtHargaSatuan.getText() + "','"
                        + txtCariPengiriman.getText() + "','"
                        + txtTujuan.getText() + "','"
                        + txtJmlBarang.getText() + "','"
                        + txtJmlHarga.getText() + "','"
                        + txtHrgKirim.getText() + "')";
                int vHasil = st.executeUpdate(sql);
                if (vHasil > 0) {
                    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambah");
                }
                setAwalForm();
                tampilTabel();
                con.close();
            } catch (SQLException | HeadlessException e) {

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tidak Dapat Di Enkripsi", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            setAwalForm();
            tampilTabel();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
         String password = "adminadmin";
        int confirm = JOptionPane.showOptionDialog(frame,
                "Apakah Anda Ingin Mengubah Data Transaksi ?",
                "Confirmation", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
            String text1 = enkrip.enkripText (txtCariKodeA3L.getText(), password);
            String text2 = enkrip.enkripText(txtKota.getText(), password);
            String text3 = enkrip.enkripText(txtTelepon.getText(), password);
            String text4 = enkrip.enkripText(txtCariBarang.getText(), password);
            String text5 = enkrip.enkripText(txtNamaBarang.getText(), password);
            String text6 = enkrip.enkripText(txtHargaSatuan.getText(), password);
            String text7 = enkrip.enkripText(txtCariPengiriman.getText(), password);
            String text8 = enkrip.enkripText(txtTujuan.getText(), password);  
            String text9 = enkrip.enkripText(txtJmlBarang.getText(), password);
            String text10 = enkrip.enkripText(txtJmlHarga.getText(), password);
            String text11 = enkrip.enkripText(txtHrgKirim.getText(), password);
            
            txtCariKodeA3L.setText(text1);
            txtKota.setText(text2);
            txtTelepon.setText(text3);
            txtCariBarang.setText(text4);
            txtNamaBarang.setText(text5);
            txtHargaSatuan.setText(text6);
            txtCariPengiriman.setText(text7);
            txtTujuan.setText(text8);
            
            txtJmlBarang.setText(text9);
            txtJmlHarga.setText(text10);
            txtHrgKirim.setText(text11);
            SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
                String Tanggal = String.valueOf(format.format(waktu.getDate()));
                Koneksi objK = new Koneksi();
                Connection con = objK.getConnection();
                Statement st = con.createStatement();//menulis statement harus melalui objek koneksi// langkah 3
                String sql = "Update transaksi set Tanggal='" + Tanggal + "', Kode_A3L='" + txtCariKodeA3L.getText() + "', kota='" + txtKota.getText() + "', telepon='" + txtTelepon.getText() + "', Kode_Barang='" + txtCariBarang.getText() + "', Nama_Barang='" + txtNamaBarang.getText() + "', Harga='" + txtHargaSatuan.getText() + "', Kode_Pengiriman='" + txtCariPengiriman.getText() + "', Tujuan_Pengiriman='" + txtTujuan.getText() +"', Jml_Barang='" + txtJmlBarang.getText() + "', Jml_Harga='" + txtJmlHarga.getText() + "', HrgPengiriman='" + txtHrgKirim.getText()+"' Where No_Kwitansi='" + txtNoKwitansi.getText() + "';";
//                System.out.println("sql " + sql);
                int vHasil = st.executeUpdate(sql);//langkah 5, sql dari string yg dipakai untuk insert barang tadi
                if (vHasil > 0) {//langkah 6
                    JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                }
                setAwalForm();
                tampilTabel();
                con.close();
            } catch (SQLException | HeadlessException e) {
                System.out.println(e.toString());
            }
        } else if (confirm == JOptionPane.NO_OPTION) {
            setAwalForm();
            tampilTabel();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tabeltransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeltransaksiMouseClicked
        // TODO add your handling code here:
         try {
            DefaultTableModel model = (DefaultTableModel) tabeltransaksi.getModel();
            int seectedRow = tabeltransaksi.getSelectedRow();
            //if (evt.getClickCount() == 2) {
                txtNoKwitansi.setText(tabeltransaksi.getValueAt(tabeltransaksi.getSelectedRow(), 0).toString());
                Date date = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(seectedRow, 1).toString());
                waktu.setDate(date);
                txtCariKodeA3L.setText(tabeltransaksi.getValueAt(tabeltransaksi.getSelectedRow(), 2).toString());
                txtKota.setText(tabeltransaksi.getValueAt(tabeltransaksi.getSelectedRow(), 3).toString());
                txtTelepon.setText(tabeltransaksi.getValueAt(tabeltransaksi.getSelectedRow(), 4).toString());
                txtCariBarang.setText(tabeltransaksi.getValueAt(tabeltransaksi.getSelectedRow(), 5).toString());
                txtNamaBarang.setText(tabeltransaksi.getValueAt(tabeltransaksi.getSelectedRow(), 6).toString());
                txtHargaSatuan.setText(tabeltransaksi.getValueAt(tabeltransaksi.getSelectedRow(), 7).toString());
                txtCariPengiriman.setText(tabeltransaksi.getValueAt(tabeltransaksi.getSelectedRow(), 8).toString());
                txtTujuan.setText(tabeltransaksi.getValueAt(tabeltransaksi.getSelectedRow(), 9).toString());
                txtJmlBarang.setText(tabeltransaksi.getValueAt(tabeltransaksi.getSelectedRow(), 10).toString());
                txtJmlHarga.setText(tabeltransaksi.getValueAt(tabeltransaksi.getSelectedRow(), 11).toString());
                txtHrgKirim.setText(tabeltransaksi.getValueAt(tabeltransaksi.getSelectedRow(), 12).toString());
                //                txtKode_Barang.setEditable(false);
                btnEdit.setEnabled(true);
                btnSimpan.setEnabled(false);
                btnHapus.setEnabled(true);
                btnBatal.setEnabled(true);
                btnDekrip.setEnabled(true);
                txtKota.requestFocus();
                //}
        } catch (ParseException ex) {
            Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabeltransaksiMouseClicked

    private void txtHrgKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHrgKirimActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txtHrgKirimActionPerformed

    private void btnDekripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDekripActionPerformed
        // TODO add your handling code here:
        
        String password = "adminadmin";

        String text1 = enkrip.deskripText(txtCariKodeA3L.getText(), password);
        String text2 = enkrip.deskripText(txtKota.getText(), password);
        String text3 = enkrip.deskripText(txtTelepon.getText(), password);
        String text4 = enkrip.deskripText(txtCariBarang.getText(), password);
        String text5 = enkrip.deskripText(txtNamaBarang.getText(), password);
        String text6 = enkrip.deskripText(txtHargaSatuan.getText(), password);
        String text7 = enkrip.deskripText(txtCariPengiriman.getText(), password);
        String text8 = enkrip.deskripText(txtTujuan.getText(), password);
        String text9 = enkrip.deskripText(txtJmlBarang.getText(), password);
        String text10 = enkrip.deskripText(txtJmlHarga.getText(), password);
        String text11 = enkrip.deskripText(txtHrgKirim.getText(), password);
       
            txtCariKodeA3L.setText(text1);
            txtKota.setText(text2);
            txtTelepon.setText(text3);
            txtCariBarang.setText(text4);
            txtNamaBarang.setText(text5);
            txtHargaSatuan.setText(text6);
            txtCariPengiriman.setText(text7);
            txtTujuan.setText(text8);
            txtJmlBarang.setText(text9);
            txtJmlHarga.setText(text10);
            txtHrgKirim.setText(text11);

    }//GEN-LAST:event_btnDekripActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showOptionDialog(frame,
                "Apakah Anda Ingin Menghapus Data ?",
                "Confirmation", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Koneksi objK = new Koneksi();
                Connection con = objK.getConnection();
                Statement st = con.createStatement();//menulis statement harus melalui objek koneksi// langkah 3
                String sql = "Delete from transaksi Where " + "No_Kwitansi='" + txtNoKwitansi.getText() + "'";
                int vHasil = st.executeUpdate(sql);//langkah 5, sql dari string yg dipakai untuk insert barang tadi
                if (vHasil > 0) {//langkah 6
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                }
                setAwalForm();
                tampilTabel();
                con.close();
            } catch (SQLException | HeadlessException e) {

            }
        }    
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        setAwalForm();
        tampilTabel();     
    }//GEN-LAST:event_btnBatalActionPerformed

    public void uang() {
        String tampung_harga = txtJmlHarga.getText();
        try {
            double harga = Double.parseDouble(txtJmlHarga.getText());
            DecimalFormat df = (DecimalFormat) DecimalFormat.getCurrencyInstance();
            DecimalFormatSymbols dfs = new DecimalFormatSymbols();
            dfs.setCurrencySymbol("");
            dfs.setMonetaryDecimalSeparator(',');
            dfs.setGroupingSeparator('.');
            df.setDecimalFormatSymbols(dfs);
            String hsl = "Rp." + df.format(harga);
            txtJmlHarga.setText(hsl);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Pengisian harga tidak boleh kosong");
        }
    }
    
     void setAwalForm() {
        txtNoKwitansi.setEnabled(false);
        waktu.setDate(null);
        txtCariKodeA3L.setText("");
        txtKota.setText("");
        txtTelepon.setText("");
        txtCariBarang.setText("");
        txtNamaBarang.setText("");
        txtHargaSatuan.setText("");
        txtCariPengiriman.setText("");
        txtTujuan.setText("");
        txtJmlBarang.setText("");
        txtJmlHarga.setText("");
        txtHrgKirim.setText("");
        txtCariKodeA3L.requestFocus();
        btnSimpan.setEnabled(true);
        btnBatal.setEnabled(true);
        btnHapus.setEnabled(false);
        btnDekrip.setEnabled(false);
        btnEdit.setEnabled(false);

        autoNumber();
        tampilTabel();
        hapusTabel();
    }

    void tampilTabel() {
        try {
            Koneksi objK = new Koneksi();
            Connection con = objK.getConnection();
            Statement st = con.createStatement();
            String sql = "Select * from transaksi order by No_Kwitansi";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String No_Kwitansi = rs.getString("No_Kwitansi");
                String Tanggal = rs.getString("Tanggal");
                String Kode_A3L = rs.getString("Kode_A3L");
                String Kota = rs.getString("Kota");
                String Telepon = rs.getString("Telepon");
                String Kode_Barang = rs.getString("Kode_Barang");
                String Nama_Barang = rs.getString("Nama_Barang");
                String Harga = rs.getString("Harga");
                String Kode_Pengiriman = rs.getString("Kode_Pengiriman");
                String Tujuan_Pengiriman = rs.getString("Tujuan_Pengiriman");
                String Jml_Barang = rs.getString("Jml_Barang");
                String Jml_Harga = rs.getString("Jml_Harga");
                String HrgPengiriman = rs.getString("HrgPengiriman");
                String[] data = {No_Kwitansi, Tanggal, Kode_A3L, Kota, Telepon, Kode_Barang, Nama_Barang, Harga, Kode_Pengiriman, Tujuan_Pengiriman , Jml_Barang, Jml_Harga, HrgPengiriman};
                tampil.addRow(data);
                
            }
            rs.close();
            con.close();
        } catch (SQLException | HeadlessException e) {

        }
    }


    void autoNumber() {
        try {
            Koneksi objK = new Koneksi();
            Connection con = objK.getConnection();
            Statement st = con.createStatement();
            String sql = "select * from transaksi order by No_Kwitansi DESC";
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                String kd = rs.getString("No_Kwitansi");
                int No_Kwitansi = Integer.parseInt(kd) + 1;
                txtNoKwitansi.setText(String.valueOf(No_Kwitansi));
                rs.close();
                con.close();
            } else {
                txtNoKwitansi.setText("1");
            }
        } catch (Exception e) {
        }

    }

    void hapusTabel() {
        int brs = tampil.getRowCount();
        for (int i = 0; i < brs; i++) {
            tampil.removeRow(0);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCariA3L;
    private javax.swing.JButton btnCariBarang;
    private javax.swing.JButton btnCariTujuan;
    private javax.swing.JButton btnDekrip;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabeltransaksi;
    private javax.swing.JTextField txtCariBarang;
    private javax.swing.JTextField txtCariKodeA3L;
    private javax.swing.JTextField txtCariPengiriman;
    private javax.swing.JTextField txtHargaSatuan;
    private javax.swing.JTextField txtHrgKirim;
    private javax.swing.JTextField txtJmlBarang;
    private javax.swing.JTextField txtJmlHarga;
    private javax.swing.JTextField txtKota;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtNoKwitansi;
    private javax.swing.JTextField txtTelepon;
    private javax.swing.JTextField txtTujuan;
    private com.toedter.calendar.JDateChooser waktu;
    // End of variables declaration//GEN-END:variables
}
